from typing import Any, List

from pydantic import RootModel

from .models import (
    FMPAcquisitionOwnership,
    FMPAftermarketQuote,
    FMPAftermarketTrade,
    FMPAnalystEstimates,
    FMPAsReportedBalanceSheet,
    FMPAsReportedCashFlowStatement,
    FMPAsReportedFullStatement,
    FMPAsReportedIncomeStatement,
    FMPBalanceSheetGrowth,
    FMPBalanceSheetStatement,
    FMPBulkDCF,
    FMPBulkEarningsSurprise,
    FMPBulkEOD,
    FMPBulkETFHolder,
    FMPBulkPriceTargetSummary,
    FMPBulkRating,
    FMPBulkStockPeers,
    FMPBulkUpgradeDowngradeConsensus,
    FMPCashFlowGrowth,
    FMPCashFlowStatement,
    FMPCommitmentOfTradersAnalysis,
    FMPCommitmentOfTradersReport,
    FMPCommodityListItem,
    FMPCompanyCIKSearch,
    FMPCompanyNameSearch,
    FMPCompanyNote,
    FMPCompanyProfile,
    FMPCompanySECFilings,
    FMPCountry,
    FMPCrowdfundingCampaign,
    FMPCrowdfundingSearch,
    FMPCryptocurrencyListItem,
    FMPCusipSearch,
    FMPDCFCustomValuation,
    FMPDcfValuation,
    FMPDelistedCompany,
    FMPDisclosureFiling,
    FMPDividend,
    FMPDividendCalendarEvent,
    FMPEarningsCalendarEvent,
    FMPEarningsTranscript,
    FMPEarningsTranscriptBySymbol,
    FMPEarningsTranscriptList,
    FMPEconomicCalendarEvent,
    FMPEconomicIndicator,
    FMPEmployeeCount,
    FMPEnterpriseValue,
    FMPEquityOffering,
    FMPEquityOfferingSearch,
    FMPESGBenchmark,
    FMPESGFiling,
    FMPESGRating,
    FMPExchangeInfo,
    FMPExchangeMarketHours,
    FMPExecutiveCompensation,
    FMPExecutiveCompensationBenchmark,
    FMPExecutiveProfile,
    FMPFinancialRatios,
    FMPFinancialRatiosTTM,
    FMPFinancialReportDate,
    FMPFinancialScores,
    FMPFinancialStatementSymbolList,
    FMPForexPair,
    FMPForm13FAnalytics,
    FMPForm13FDate,
    FMPForm13FExtract,
    FMPForm13FFiling,
    FMPFullFinancialReport,
    FMPFundAssetExposure,
    FMPFundCountryAllocation,
    FMPFundDisclosure,
    FMPFundDisclosureDate,
    FMPFundDisclosureNameSearch,
    FMPFundHolder,
    FMPFundHolding,
    FMPFundInfo,
    FMPFundSectorWeighting,
    FMPHistoricalDataPointFull,
    FMPHistoricalDataPointLight,
    FMPHistoricalEmployeeCount,
    FMPHistoricalIndexConstituent,
    FMPHistoricalIndustryPE,
    FMPHistoricalIndustryPerformance,
    FMPHistoricalRating,
    FMPHistoricalSectorPE,
    FMPHistoricalSectorPerformance,
    FMPHistoricalSentiment,
    FMPHistoricalStockGrade,
    FMPHolderIndustryBreakdown,
    FMPHolderPerformance,
    FMPIncomeStatement,
    FMPIncomeStatementGrowth,
    FMPIndexConstituent,
    FMPIndexListItem,
    FMPIndustry,
    FMPIndustryClassification,
    FMPIndustryClassificationSearch,
    FMPIndustryPerformanceSnapshot,
    FMPIndustryPerformanceSummary,
    FMPIndustryPESnapshot,
    FMPInsiderTrade,
    FMPInsiderTradeStatistics,
    FMPInsiderTransactionType,
    FMPIntradayDataPoint,
    FMPIsinSearch,
    FMPKeyMetrics,
    FMPKeyMetricsTTM,
    FMPLatestFinancialStatement,
    FMPMarketCap,
    FMPMarketMover,
    FMPMarketRiskPremium,
    FMPMergerAcquisition,
    FMPNewsArticle,
    FMPOwnerEarnings,
    FMPPoliticalTrade,
    FMPPositionSummary,
    FMPPriceTargetConsensus,
    FMPPriceTargetNews,
    FMPPriceTargetSummary,
    FMPProspectusFiling,
    FMPQuoteFull,
    FMPQuoteShort,
    FMPRatingSnapshot,
    FMPRevenueSegmentation,
    FMPSector,
    FMPSectorPerformanceSnapshot,
    FMPSectorPESnapshot,
    FMPShareFloat,
    FMPStockGrade,
    FMPStockGradeNews,
    FMPStockGradeSummary,
    FMPStockPeer,
    FMPStockPriceChange,
    FMPStockScreenerResult,
    FMPStockSplit,
    FMPSymbolAndCIKList,
    FMPSymbolAndCompanyNameList,
    FMPSymbolAndNameList,
    FMPSymbolChange,
    FMPSymbolSearch,
    FMPTechnicalIndicator,
    FMPTreasuryRates,
    FMPTrendingSentiment,
    FMPUpcomingIPO,
)

ENDPOINT_MODEL_MAP = {
    # Search
    "search_symbol": RootModel[List[FMPSymbolSearch]],
    "search_name": RootModel[List[FMPCompanyNameSearch]],
    "search_cik": RootModel[List[FMPCompanyCIKSearch]],
    "search_cusip": RootModel[List[FMPCusipSearch]],
    "search_isin": RootModel[List[FMPIsinSearch]],
    "company_screener": RootModel[List[FMPStockScreenerResult]],
    "search_exchange_variants": RootModel[List[FMPCompanyProfile]],
    # Directory
    "stock_list": RootModel[List[FMPSymbolAndCompanyNameList]],
    "financial_statement_symbol_list": RootModel[List[FMPFinancialStatementSymbolList]],
    "cik_list": RootModel[List[FMPSymbolAndCIKList]],
    "symbol_change": RootModel[List[FMPSymbolChange]],
    "etf_list": RootModel[List[FMPSymbolAndNameList]],
    "actively_trading_list": RootModel[List[FMPSymbolAndNameList]],
    "available_exchanges": RootModel[List[FMPExchangeInfo]],
    "available_sectors": RootModel[List[FMPSector]],
    "available_industries": RootModel[List[FMPIndustry]],
    "available_countries": RootModel[List[FMPCountry]],
    "available_indexes": RootModel[List[FMPSymbolAndNameList]],
    # Analyst
    "analyst_estimates": RootModel[List[FMPAnalystEstimates]],
    "ratings_snapshot": RootModel[List[FMPRatingSnapshot]],
    "ratings_historical": RootModel[List[FMPHistoricalRating]],
    "price_target_summary": RootModel[List[FMPPriceTargetSummary]],
    "price_target_consensus": RootModel[List[FMPPriceTargetConsensus]],
    "price_target_news": RootModel[List[FMPPriceTargetNews]],
    "price_target_latest_news": RootModel[List[FMPPriceTargetNews]],
    "stock_grades": RootModel[List[FMPStockGrade]],
    "historical_stock_grades": RootModel[List[FMPHistoricalStockGrade]],
    "stock_grades_summary": RootModel[List[FMPStockGradeSummary]],
    "stock_grade_news": RootModel[List[FMPStockGradeNews]],
    "stock_grade_latest_news": RootModel[List[FMPStockGradeNews]],
    # Calendar
    "dividends": RootModel[List[FMPDividend]],
    "dividends_calendar": RootModel[List[FMPDividendCalendarEvent]],
    "earnings_calendar": RootModel[List[FMPEarningsCalendarEvent]],
    "ipos_calendar": RootModel[List[FMPUpcomingIPO]],
    "ipos_disclosure": RootModel[List[FMPDisclosureFiling]],
    "ipos_prospectus": RootModel[List[FMPProspectusFiling]],
    "splits": RootModel[List[FMPStockSplit]],
    "splits_calendar": RootModel[List[FMPStockSplit]],
    # Chart
    "historical_price_eod_light": RootModel[List[FMPHistoricalDataPointLight]],
    "historical_price_eod": RootModel[List[FMPHistoricalDataPointFull]],
    "historical_price_eod_non_split_adjusted": RootModel[
        List[FMPHistoricalDataPointFull]
    ],
    "historical_price_eod_dividend_adjusted": RootModel[
        List[FMPHistoricalDataPointFull]
    ],
    "historical_chart": RootModel[List[FMPIntradayDataPoint]],
    # Company
    "company_profile": RootModel[List[FMPCompanyProfile]],
    "company_profile_cik": RootModel[List[FMPCompanyProfile]],
    "company_notes": RootModel[List[FMPCompanyNote]],
    "stock_peers": RootModel[List[FMPStockPeer]],
    "delisted_companies": RootModel[List[FMPDelistedCompany]],
    "employee_count": RootModel[List[FMPEmployeeCount]],
    "historical_employee_count": RootModel[List[FMPHistoricalEmployeeCount]],
    "market_capitalization": RootModel[List[FMPMarketCap]],
    "market_capitalization_batch": RootModel[List[FMPMarketCap]],
    "historical_market_capitalization": RootModel[List[FMPMarketCap]],
    "shares_float": RootModel[List[FMPShareFloat]],
    "shares_float_all": RootModel[List[FMPShareFloat]],
    "mergers_acquisitions": RootModel[List[FMPMergerAcquisition]],
    "mergers_acquisitions_search": RootModel[List[FMPMergerAcquisition]],
    "key_executives": RootModel[List[FMPExecutiveProfile]],
    "key_executives_compensation": RootModel[List[FMPExecutiveCompensation]],
    "executive_compensation_benchmark": RootModel[
        List[FMPExecutiveCompensationBenchmark]
    ],
    # Commitment Of Traders
    "commitment_of_traders_report": RootModel[List[FMPCommitmentOfTradersReport]],
    "commitment_of_traders_report_analysis": RootModel[
        List[FMPCommitmentOfTradersAnalysis]
    ],
    "commitment_of_traders_report_list": RootModel[List[FMPSymbolAndNameList]],
    # Discounted Cash Flow
    "discounted_cash_flow_valuation": RootModel[List[FMPDcfValuation]],
    "discounted_cash_flow_levered": RootModel[List[FMPDcfValuation]],
    "discounted_cash_flow_custom": RootModel[List[FMPDCFCustomValuation]],
    "discounted_cash_flow_custom_levered": RootModel[List[FMPDCFCustomValuation]],
    # Economics
    "treasury_rates": RootModel[List[FMPTreasuryRates]],
    "economic_indicators": RootModel[List[FMPEconomicIndicator]],
    "economic_calendar": RootModel[List[FMPEconomicCalendarEvent]],
    "market_risk_premium": RootModel[List[FMPMarketRiskPremium]],
    # ESG
    "esg_disclosures": RootModel[List[FMPESGFiling]],
    "esg_ratings": RootModel[List[FMPESGRating]],
    "esg_benchmark": RootModel[List[FMPESGBenchmark]],
    # ETF & Mutual Funds
    "etf_holdings": RootModel[List[FMPFundHolding]],
    "etf_info": RootModel[List[FMPFundInfo]],
    "etf_country_weightings": RootModel[List[FMPFundCountryAllocation]],
    "etf_asset_exposure": RootModel[List[FMPFundAssetExposure]],
    "etf_sector_weightings": RootModel[List[FMPFundSectorWeighting]],
    "funds_disclosure_holders_latest": RootModel[List[FMPFundHolder]],
    "funds_disclosure": RootModel[List[FMPFundDisclosure]],
    "funds_disclosure_holders_search": RootModel[List[FMPFundDisclosureNameSearch]],
    "funds_disclosure_dates": RootModel[List[FMPFundDisclosureDate]],
    # Commodity
    "commodity_list": RootModel[List[FMPCommodityListItem]],
    # Fundraisers
    "crowdfunding_offerings_latest": RootModel[List[FMPCrowdfundingCampaign]],
    "crowdfunding_offerings_search": RootModel[List[FMPCrowdfundingSearch]],
    "crowdfunding_offerings": RootModel[List[FMPCrowdfundingCampaign]],
    "fundraising_latest": RootModel[List[FMPEquityOffering]],
    "fundraising_search": RootModel[List[FMPEquityOfferingSearch]],
    "fundraising": RootModel[List[FMPEquityOffering]],
    # Crypto
    "cryptocurrency_list": RootModel[List[FMPCryptocurrencyListItem]],
    # Forex
    "forex_list": RootModel[List[FMPForexPair]],
    # Statements
    "income_statement": RootModel[List[FMPIncomeStatement]],
    "balance_sheet_statement": RootModel[List[FMPBalanceSheetStatement]],
    "cash_flow_statement": RootModel[List[FMPCashFlowStatement]],
    "financial_statements_latest": RootModel[List[FMPLatestFinancialStatement]],
    "income_statement_ttm": RootModel[List[FMPIncomeStatement]],
    "balance_sheet_statements_ttm": RootModel[List[FMPBalanceSheetStatement]],
    "cashflow_statements_ttm": RootModel[List[FMPCashFlowStatement]],
    "key_metrics": RootModel[List[FMPKeyMetrics]],
    "financial_ratios": RootModel[List[FMPFinancialRatios]],
    "key_metrics_ttm": RootModel[List[FMPKeyMetricsTTM]],
    "financial_ratios_ttm": RootModel[List[FMPFinancialRatiosTTM]],
    "financial_scores": RootModel[List[FMPFinancialScores]],
    "owner_earnings": RootModel[List[FMPOwnerEarnings]],
    "enterprise_values": RootModel[List[FMPEnterpriseValue]],
    "income_statement_growth": RootModel[List[FMPIncomeStatementGrowth]],
    "balance_sheet_statement_growth": RootModel[List[FMPBalanceSheetGrowth]],
    "cash_flow_statement_growth": RootModel[List[FMPCashFlowGrowth]],
    "financial_growth": RootModel[List[FMPIncomeStatementGrowth]],
    "financial_reports_dates": RootModel[List[FMPFinancialReportDate]],
    "financial_reports_json": FMPFullFinancialReport,
    "revenue_product_segmentation": RootModel[List[FMPRevenueSegmentation]],
    "revenue_geographic_segmentation": RootModel[List[FMPRevenueSegmentation]],
    "income_statement_as_reported": RootModel[List[FMPAsReportedIncomeStatement]],
    "balance_sheet_statement_as_reported": RootModel[List[FMPAsReportedBalanceSheet]],
    "cash_flow_statement_as_reported": RootModel[List[FMPAsReportedCashFlowStatement]],
    "financial_statement_full_as_reported": RootModel[List[FMPAsReportedFullStatement]],
    # Form 13F
    "institutional_ownership_latest": RootModel[List[FMPForm13FFiling]],
    "institutional_ownership_extract": RootModel[List[FMPForm13FExtract]],
    "institutional_ownership_dates": RootModel[List[FMPForm13FDate]],
    "institutional_ownership_extract_analytics_by_holder": RootModel[
        List[FMPForm13FAnalytics]
    ],
    "institutional_ownership_holder_performance_summary": RootModel[
        List[FMPHolderPerformance]
    ],
    "institutional_ownership_holder_industry_breakdown": RootModel[
        List[FMPHolderIndustryBreakdown]
    ],
    "institutional_ownership_positions_summary": RootModel[List[FMPPositionSummary]],
    "institutional_ownership_industry_summary": RootModel[
        List[FMPIndustryPerformanceSummary]
    ],
    # Indexes
    "index_list": RootModel[List[FMPIndexListItem]],
    "index_constituents": RootModel[List[FMPIndexConstituent]],
    "index_constituents_historical": RootModel[List[FMPHistoricalIndexConstituent]],
    # Insider Trades
    "insider_trading": RootModel[List[FMPInsiderTrade]],
    "insider_trading_latest": RootModel[List[FMPInsiderTrade]],
    "insider_trading_reporting_name": RootModel[List[Any]],
    "insider_trading_transaction_type": RootModel[List[FMPInsiderTransactionType]],
    "insider_trading_statistics": RootModel[List[FMPInsiderTradeStatistics]],
    "acquisition_ownership": RootModel[List[FMPAcquisitionOwnership]],
    # Market Performance
    "sector_performance_snapshot": RootModel[List[FMPSectorPerformanceSnapshot]],
    "industry_performance_snapshot": RootModel[List[FMPIndustryPerformanceSnapshot]],
    "historical_sector_performance": RootModel[List[FMPHistoricalSectorPerformance]],
    "historical_industry_performance": RootModel[
        List[FMPHistoricalIndustryPerformance]
    ],
    "sector_pe_snapshot": RootModel[List[FMPSectorPESnapshot]],
    "industry_pe_snapshot": RootModel[List[FMPIndustryPESnapshot]],
    "historical_sector_pe": RootModel[List[FMPHistoricalSectorPE]],
    "historical_industry_pe": RootModel[List[FMPHistoricalIndustryPE]],
    "biggest_gainers": RootModel[List[FMPMarketMover]],
    "biggest_losers": RootModel[List[FMPMarketMover]],
    "most_active_stocks": RootModel[List[FMPMarketMover]],
    # Market Hours
    "exchange_market_hours": RootModel[List[Any]],
    "holidays_by_exchange": RootModel[List[Any]],
    "all_exchange_market_hours": RootModel[List[FMPExchangeMarketHours]],
    # News
    "news_stock": RootModel[List[FMPNewsArticle]],
    "news_stock_latest": RootModel[List[FMPNewsArticle]],
    "company_press_releases": RootModel[List[FMPNewsArticle]],
    "company_press_releases_latest": RootModel[List[FMPNewsArticle]],
    "news_general_latest": RootModel[List[FMPNewsArticle]],
    "news_crypto": RootModel[List[FMPNewsArticle]],
    "news_crypto_latest": RootModel[List[FMPNewsArticle]],
    "news_forex": RootModel[List[FMPNewsArticle]],
    "social_sentiment": RootModel[List[FMPHistoricalSentiment]],
    "social_sentiment_trending": RootModel[List[FMPTrendingSentiment]],
    "trending_sentiment": RootModel[List[FMPTrendingSentiment]],
    # Technical Indicators
    "technical_indicators": RootModel[List[FMPTechnicalIndicator]],
    # Quote
    "quote": RootModel[List[FMPQuoteFull]],
    "quote_short": RootModel[List[FMPQuoteShort]],
    "aftermarket_trade": RootModel[List[FMPAftermarketTrade]],
    "aftermarket_quote": RootModel[List[FMPAftermarketQuote]],
    "stock_price_change": RootModel[List[FMPStockPriceChange]],
    "stock_batch_quote": RootModel[List[FMPQuoteFull]],
    "batch_quote_short": RootModel[List[FMPQuoteShort]],
    "batch_aftermarket_trade": RootModel[List[FMPAftermarketTrade]],
    "batch_aftermarket_quote": RootModel[List[FMPAftermarketQuote]],
    "batch_exchange_quote": RootModel[List[FMPQuoteShort]],
    "batch_mutual_fund_quote": RootModel[List[FMPQuoteShort]],
    "batch_etf_quote": RootModel[List[FMPQuoteShort]],
    "batch_commodity_quote": RootModel[List[FMPQuoteShort]],
    "batch_crypto_quote": RootModel[List[FMPQuoteShort]],
    "batch_forex_quote": RootModel[List[FMPQuoteShort]],
    "batch_index_quote": RootModel[List[FMPQuoteShort]],
    # SEC Filings
    "sec_rss_feeds": RootModel[List[Any]],
    "sec_filings_8k": RootModel[List[Any]],
    "sec_filings_financials": RootModel[List[Any]],
    "sec_filings_search_form_type": RootModel[List[Any]],
    "sec_filings_search_symbol": RootModel[List[Any]],
    "sec_filings_search_cik": RootModel[List[Any]],
    "sec_filings_company_search_name": RootModel[List[FMPCompanySECFilings]],
    "sec_filings_company_search_symbol": RootModel[List[FMPCompanySECFilings]],
    "sec_filings_company_search_cik": RootModel[List[FMPCompanySECFilings]],
    "sec_profile": RootModel[List[FMPCompanyProfile]],
    "industry_classification_list": RootModel[List[FMPIndustryClassification]],
    "industry_classification_search": RootModel[List[FMPIndustryClassificationSearch]],
    "industry_classification_all": RootModel[List[FMPIndustryClassification]],
    # Earnings Transcript
    "earnings_transcript_latest": RootModel[List[FMPEarningsTranscript]],
    "earnings_transcript": RootModel[List[FMPEarningsTranscript]],
    "earnings_transcript_by_symbol": RootModel[List[FMPEarningsTranscriptBySymbol]],
    "earnings_transcript_list": RootModel[List[FMPEarningsTranscriptList]],
    # Senate
    "senate_latest": RootModel[List[FMPPoliticalTrade]],
    "house_latest": RootModel[List[FMPPoliticalTrade]],
    "senate_trades": RootModel[List[FMPPoliticalTrade]],
    "senate_trades_by_name": RootModel[List[FMPPoliticalTrade]],
    "house_trades": RootModel[List[FMPPoliticalTrade]],
    "house_trades_by_name": RootModel[List[FMPPoliticalTrade]],
    # Bulk
    "bulk_profiles": RootModel[List[FMPCompanyProfile]],
    "profile_bulk": RootModel[List[FMPCompanyProfile]],
    "rating_bulk": RootModel[List[FMPBulkRating]],
    "dcf_bulk": RootModel[List[FMPBulkDCF]],
    "scores_bulk": RootModel[List[FMPFinancialScores]],
    "price_target_summary_bulk": RootModel[List[FMPBulkPriceTargetSummary]],
    "etf_holder_bulk": RootModel[List[FMPBulkETFHolder]],
    "upgrades_downgrades_consensus_bulk": RootModel[
        List[FMPBulkUpgradeDowngradeConsensus]
    ],
    "key_metrics_ttm_bulk": RootModel[List[FMPKeyMetricsTTM]],
    "ratios_ttm_bulk": RootModel[List[FMPFinancialRatiosTTM]],
    "peers_bulk": RootModel[List[FMPBulkStockPeers]],
    "earnings_surprises_bulk": RootModel[List[FMPBulkEarningsSurprise]],
    "income_statement_bulk": RootModel[List[FMPIncomeStatement]],
    "income_statement_growth_bulk": RootModel[List[FMPIncomeStatementGrowth]],
    "balance_sheet_statement_bulk": RootModel[List[FMPBalanceSheetStatement]],
    "balance_sheet_statement_growth_bulk": RootModel[List[FMPBalanceSheetGrowth]],
    "cash_flow_statement_bulk": RootModel[List[FMPCashFlowStatement]],
    "cash_flow_statement_growth_bulk": RootModel[List[FMPCashFlowGrowth]],
    "eod_bulk": RootModel[List[FMPBulkEOD]],
}
