# Run black in --check mode on pull requests and pushes to master.
# This workflow should fail on any black violations.
name: Black Check
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        set -xe
        python -VV
        python -m site
        python -m pip install --upgrade pip
        pip install black
    - name: Run black
      run: |
        black fmpsdk --check --exclude "venv|build"
